# -*- coding: utf-8 -*-
"""combineTrainingData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxUzNOSsHuVRBM8RPn-JFATJPYXVJvP3
"""

import pandas as pd
import numpy as np
import os
import re

### Helper functions
def getSubjectId(path):
  lstFile = []
  for f in os.listdir(path):
    if re.search(".*_x_time.csv", f, re.I):
      lstFile.append((f.split('_')[1], f.split('_')[2]))
  return lstFile


def generate_target(x, x_size):
  tg = []
  for t in x:
    if t == 0:
      [tg.append(0) for i in range(0,4)]
    elif t == 1:
      [tg.append(1) for i in range(0,4)]
    elif t == 2:
      [tg.append(2) for i in range(0,4)]
    else:
      [tg.append(3) for i in range(0,4)]

  if len(tg) >= x_size:
    return tg[:x_size]
  else:
    tg.append(tg[-1])
    return tg

def combineSubjectData(train_path_r = '/', train_path_w = '/'):
  cols = ['xA','yA','zA', 'xG','yG','zG']
  trainingSubjects = getSubjectId(train_path_r)

  # preparating training data
  df = pd.DataFrame()
  train_df = pd.DataFrame()

  for s,r in trainingSubjects:
    x_df = pd.read_csv(os.path.join(train_path_r,'subject_{}_{}__x.csv'.format(s,r)),header =None)
    x_time_df = pd.read_csv(os.path.join(train_path_r,'subject_{}_{}__x_time.csv'.format(s,r)), header = None)
    y_df = pd.read_csv(os.path.join(train_path_r,'subject_{}_{}__y.csv'.format(s,r)), header = None)
    x_df.columns = cols
    x_time_df.columns = ['time']
    y_df.columns = ['target']
    target = generate_target(y_df['target'], x_time_df.shape[0])

    ## merge
    x_df = x_time_df.merge(x_df, left_index=True,right_index=True)
    x_df['y'] = target

    train_df = pd.concat([train_df, x_df], axis = 0)


  # writing to the given path
  train_df.to_csv(train_path_w+'raw_train_data_all_Subjects.csv', index = False)

